### ISSUE TITLE
Miniloader outputting on one lane only?

### ISSUE THREAD

**Issue by evandy0** [mspielberg/factorio-miniloader#24] opened 2019-05-22 11:46 UTC
Just had a weird issue while building an ore crushing facility w/ Angels mod.    After blueprinting and putting down ~60 filter miniloaders, once I hooked it up they all started outputting on the left-hand side of the belt only.   I was able to "fix" it by unchecking the override stack size box (really annoying with 50 of them), although I noticed that the box re-checked itself automatically shortly after that.

**Comment by evandy0** [comment] 2019-05-22 11:52
I don't have a save from when they were all doing it (sorry), but have a look at the 6th sorter down in the 4th and 5th columns of ore sorters.  (They stand out with Bottleneck as they show they are output starved even though the belt has a free lane).  The Stiratite output filter is doing the bad behavior.

[Miniloader_bug.zip](https://github.com/mspielberg/factorio-miniloader/files/3207194/Miniloader_bug.zip)

**Comment by evandy0** [comment] 2019-05-22 11:57
In case it matters, when I built this I forgot to set the filters, so my process was:
1) Build module including filter loaders.
2) Replicate module into the matrix
3) go "oh heck" and set the filters on one of them, then copy/paste with the 0.17 function on top of the rest of everything by holding the left mouse button by running up and down.

Maybe the issue is that this process somehow only set the filters on 1/2 of the internal invisible inserters??

**Comment by mspielberg** [comment] 2019-06-03 15:44
Thanks for the report! I think the problem is related to use of the 0.17 paste tool on top of already built miniloaders. I’ll have a deeper look.

I would bet that the older shift+LMB/RMB method of copying settings would have worked as expected.

**Comment by mspielberg** [comment] 2019-06-10 19:47
Should be fixed in 1.7.10.

**Closed as completed by mspielberg** 2019-06-10 19:47 UTC
